import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import ts from 'typescript';
function load(file, deps = {}) {
  const module = { exports: {} };
  const code = ts.transpileModule(readFileSync(new URL(file, import.meta.url), 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
  new Function('require', 'exports', 'module', code)(name => { if (!(name in deps)) throw new Error(name); return deps[name]; }, module.exports, module);
  return module.exports;
}
const sql = new DatabaseSync(':memory:');
for (const migration of ['0010_profile_metadata', '0011_metadata_error', '0012_instagram_fallback']) sql.exec(readFileSync(new URL(`../drizzle/${migration}.sql`, import.meta.url), 'utf8'));
const db = { prepare(query) { let values = []; return { bind(...v) { values = v; return this; }, async run() { return sql.prepare(query).run(...values); }, async all() { return { results: sql.prepare(query).all(...values) }; } }; } };
let calls = 0;
const gate = load('../lib/instagram-fetch.ts', { '@/lib/submissions': { submissionsDb: () => db }, '@/lib/profile-metadata': { fetchProfilePage: async () => { calls++; throw new Error('Крыніца недаступная: 429'); } } });
await assert.rejects(gate.fetchInstagramPage('https://instagram.com/one'), /6 гадзін/);
await assert.rejects(gate.fetchInstagramPage('https://instagram.com/two'), /паўза/);
assert.equal(calls, 1);
assert.ok(sql.prepare('SELECT next_attempt_at FROM instagram_fetch_state').get().next_attempt_at > Date.now() + 5 * 3600000);
sql.exec('UPDATE instagram_fetch_state SET next_attempt_at = 0');
await assert.rejects(gate.fetchInstagramPage('https://instagram.com/three'), /6 гадзін/);
assert.equal(calls, 2);
const logos = load('../lib/logo-file.ts');
assert.equal(logos.logoMime(new TextEncoder().encode('<svg onload="bad()">')), null);
assert.equal(logos.logoMime(new Uint8Array(1024 * 1024 + 1)), null);
const png = new Uint8Array(12); png.set([137,80,78,71,13,10,26,10]);
assert.equal(logos.logoMime(png), 'image/png');
let stored = 0;
const route = load('../app/api/channel-logo/route.ts', { 'cloudflare:workers': { env: { LOGOS: { put: async () => { stored++; } } } }, '@/lib/submissions': { submissionsDb: () => db }, '@/lib/refresh-profile': { refreshTargets: async () => ['https://instagram.com/test'] }, '@/lib/channel-identity': { channelIdentity: () => 'instagram:test' }, '@/lib/logo-file': logos });
const makeRequest = (headers = {}, bytes = png) => new Request('https://stage.test/api/channel-logo?channel=instagram:test', { method: 'POST', headers, body: bytes });
assert.equal((await route.POST(makeRequest())).status, 403);
const headers = { 'oai-authenticated-user-email': 'radziuk219@gmail.com', origin: 'https://stage.test' };
assert.equal((await route.POST(makeRequest({ ...headers, origin: 'https://evil.test' }))).status, 403);
assert.equal((await route.POST(makeRequest(headers, new Uint8Array(1024 * 1024 + 1)))).status, 413);
assert.equal((await route.POST(makeRequest(headers, new TextEncoder().encode('<svg onload="bad()">')))).status, 400);
const response = await route.POST(makeRequest(headers)); assert.equal(response.status, 200); assert.equal(stored, 1);
const manual = (await response.json()).avatar_url;
assert.equal(sql.prepare('SELECT manual_avatar_url FROM profile_metadata').get().manual_avatar_url, manual);
sql.exec('CREATE TABLE submissions (canonical_key TEXT, title TEXT, description TEXT, avatar_url TEXT, platform TEXT)');
let metadata = { title: 'Remote', description: 'Remote', avatarUrl: 'https://remote.test/logo', subscriberCount: 42, platform: 'Instagram' };
const refresh = load('../lib/refresh-profile.ts', { '@/lib/submissions': { submissionsDb: () => db }, '@/lib/channel-identity': { channelIdentity: () => 'instagram:test' }, '@/lib/enrich-channel': { enrichChannel: async () => metadata } });
await refresh.refreshProfile('https://instagram.com/test'); metadata = null; await refresh.refreshProfile('https://instagram.com/test');
assert.equal(sql.prepare('SELECT COALESCE(manual_avatar_url, avatar_url) AS logo FROM profile_metadata').get().logo, manual);
assert.equal(sql.prepare('SELECT subscriber_count FROM profile_metadata').get().subscriber_count, 42);
console.log('PASS: persistent cooldown, expiry, upload authorization/size/type, manual logo precedence, failed refresh preservation');
