import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import ts from 'typescript';
function load(file, deps = {}) { const module = { exports: {} }; const code = ts.transpileModule(readFileSync(new URL(file, import.meta.url), 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText; new Function('require', 'exports', 'module', code)((name) => { if (!(name in deps)) throw new Error(name); return deps[name]; }, module.exports, module); return module.exports; }
const parser = load('../lib/profile-metadata.ts');
assert.equal(parser.countValue(undefined), null); assert.equal(parser.countValue(''), null); assert.equal(parser.countValue('2M'), null); assert.equal(parser.countValue(0), 0);
for (const url of ['http://instagram.com/test', 'https://instagram.com.evil.test/test', 'https://127.0.0.1/', 'https://user@instagram.com/test', 'https://instagram.com:4433/test']) assert.equal(parser.allowedProfileUrl(url), false);
const tiktok = parser.parseProfile(`<script type="application/json">${JSON.stringify({ userInfo: { user: { uniqueId: 'test', nickname: 'Тэст', signature: 'Па-беларуску', avatarLarger: 'https://images.example/logo.jpg' }, stats: { followerCount: 442, followingCount: 99999, heartCount: 800000 } } })}</script>`, 'TikTok', 'test');
assert.equal(tiktok.subscriberCount, 442); assert.equal(tiktok.title, 'Тэст');
assert.equal(parser.parseProfile('<meta property="og:description" content="Artist • 500,000 monthly listeners">', 'Spotify', 'artist').subscriberCount, null);
assert.equal(parser.parseProfile('<meta property="og:description" content="Artist • 500,000 monthly listeners">', 'Spotify', 'artist').description, '');
assert.equal(parser.parseProfile('<meta property="og:title" content="Log in"><meta property="og:image" content="https://x.test/login.png">', 'Instagram', 'test').avatarUrl, null);
assert.equal(parser.metaValue(`<meta content='Bob &quot;Music&quot; &amp; Co' property='og:title'>`, ['og:title']), 'Bob "Music" & Co');
const ig = parser.parseProfile('<meta property="og:description" content="12,345 Followers, 99 Following - bio">', 'Instagram', 'test'); assert.equal(ig.subscriberCount, 12345);
const realFetch = globalThis.fetch;
globalThis.fetch = async () => new Response('', { status: 302, headers: { location: 'https://127.0.0.1/private' } });
await assert.rejects(parser.fetchProfilePage('https://instagram.com/test'), /Небяспечная/);
globalThis.fetch = realFetch;
const sql = new DatabaseSync(':memory:');
sql.exec(readFileSync(new URL('../drizzle/0010_profile_metadata.sql', import.meta.url), 'utf8'));
sql.exec(readFileSync(new URL('../drizzle/0011_metadata_error.sql', import.meta.url), 'utf8'));
sql.exec("CREATE TABLE submissions (canonical_key TEXT, title TEXT, description TEXT, avatar_url TEXT, platform TEXT); INSERT INTO submissions VALUES ('instagram:test', 'Manual title', 'Manual description', 'https://old.test/logo', 'Instagram')");
const db = { prepare(query) { let values = []; return { bind(...v) { values = v; return this; }, async run() { return sql.prepare(query).run(...values); } }; } };
let metadata = { title: 'Remote title', description: 'Remote description', avatarUrl: 'https://new.test/logo', subscriberCount: 100, platform: 'Instagram' };
const service = load('../lib/refresh-profile.ts', { '@/lib/submissions': { submissionsDb: () => db }, '@/lib/channel-identity': { channelIdentity: () => 'instagram:test' }, '@/lib/enrich-channel': { enrichChannel: async () => metadata } });
await service.refreshProfile('https://instagram.com/test');
assert.equal(sql.prepare('SELECT title FROM submissions').get().title, 'Manual title');
assert.equal(sql.prepare('SELECT description FROM submissions').get().description, 'Manual description');
assert.equal(sql.prepare('SELECT avatar_url FROM submissions').get().avatar_url, 'https://new.test/logo');
metadata = null;
await service.refreshProfile('https://instagram.com/test');
const preserved = sql.prepare('SELECT * FROM profile_metadata').get();
assert.equal(preserved.subscriber_count, 100); assert.equal(preserved.avatar_url, 'https://new.test/logo'); assert.equal(preserved.status, 'unavailable');
console.log('PASS: profile parsing, follower semantics, redirects, manual text, failure preservation');
