import { env } from 'cloudflare:workers';
import { submissionsDb } from '@/lib/submissions';

export type CultureCandidate={id:string;canonical_key:string;kind:'movie'|'book';title:string;release_year:number;author:string;description:string;url:string;banner_source_url:string|null;source_label:string;status:'pending'|'approved'|'rejected';discovered_at:string;reviewed_at:string|null};
type CandidateSeed=Omit<CultureCandidate,'id'|'status'|'discovered_at'|'reviewed_at'>;
const headers={'User-Agent':'KOSH-Staging/1.0 (https://belaruski-kosh.org)','Accept':'text/html,application/json'};
const clean=(s:string)=>decode(s.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim());
function decode(s:string){return s.replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16))).replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&quot;/g,'"').replace(/&#(?:39|x27);/gi,"'").replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&nbsp;/g,' ')}
async function text(url:string){const r=await fetch(url,{headers,signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`${new URL(url).hostname}: ${r.status}`);const body=await r.text();if(body.length>2_000_000)throw new Error('Адказ крыніцы занадта вялікі');return body}
function attr(html:string,key:string){const escaped=key.replace(':','\\:');const a=html.match(new RegExp(`<meta[^>]+(?:property|name)=["']${escaped}["'][^>]+content=["']([^"']*)["']`,'i'))??html.match(new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+(?:property|name)=["']${escaped}["']`,'i'));return a?decode(a[1]):''}
function titlePart(html:string){return decode(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]??'')}
function yearFrom(value:string){const years=[...value.matchAll(/\b(19\d{2}|20\d{2})\b/g)].map(x=>Number(x[1]));return years.at(-1)??new Date().getFullYear()}

async function movieSeeds(offset:number):Promise<{items:CandidateSeed[];next:number}>{
 const home=await text('https://new.kinakipa.site/');const ids=[...new Set([...home.matchAll(/href=["']\/movie\?id=(\d+)/gi)].map(x=>x[1]))];const start=offset<ids.length?offset:0,batch=ids.slice(start,start+6),items:CandidateSeed[]=[];
 for(const id of batch){const url=`https://new.kinakipa.site/movie?id=${id}`,html=await text(url),raw=titlePart(html),parts=raw.split('|').map(x=>x.trim()),title=parts[0]||`Фільм ${id}`,year=yearFrom(raw),description=attr(html,'description'),banner=attr(html,'og:image'),directorMatch=html.match(/director=[^"']+["'][^>]*>([\s\S]*?)<\/a>/i),author=directorMatch?clean(directorMatch[1]):'Рэжысёр не пазначаны';if(description&&banner)items.push({canonical_key:`kinakipa:${id}`,kind:'movie',title,release_year:year,author,description:description.slice(0,1600),url,banner_source_url:banner,source_label:'Kinakipa'})}
 return {items,next:start+batch.length>=ids.length?0:start+batch.length}
}
type StoreProduct={id:number;name:string;permalink:string;description:string;short_description?:string;images?:{src?:string;thumbnail?:string}[]};
async function bookSeeds(page:number):Promise<{items:CandidateSeed[];next:number}>{
 const url=`https://gutenbergpublisher.eu/wp-json/wc/store/v1/products?category=177&per_page=6&orderby=date&order=desc&page=${page}`;const r=await fetch(url,{headers:{...headers,Accept:'application/json'},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`Gutenberg: ${r.status}`);const products=await r.json() as StoreProduct[];const items=products.map((p)=>{const parts=decode(p.name).split(/\.\s+/),author=parts.length>1?parts.pop()!:'Аўтар не пазначаны',title=parts.join('. ')||decode(p.name),body=clean(p.short_description||p.description);return {canonical_key:`gutenberg:${p.id}`,kind:'book' as const,title,release_year:yearFrom(body),author,description:(body||'Апісанне не пазначана').slice(0,1600),url:p.permalink,banner_source_url:p.images?.[0]?.src??p.images?.[0]?.thumbnail??null,source_label:'Gutenberg Publisher'}});return {items,next:products.length<6?1:page+1}
}
export async function runCultureDiscovery(){
 const db=submissionsDb(),now=new Date().toISOString(),lease=new Date(Date.now()+180000).toISOString();await db.prepare("INSERT OR IGNORE INTO culture_discovery_state (id,lease_until) VALUES ('main','')").run();const lock=await db.prepare("UPDATE culture_discovery_state SET lease_until=? WHERE id='main' AND lease_until<? RETURNING movie_offset,book_page").bind(lease,now).all<{movie_offset:number;book_page:number}>();const state=lock.results?.[0];if(!state)throw new Error('Пошук ужо працуе');const runId=crypto.randomUUID();let found=0;const warnings:string[]=[];
 try{await db.prepare("UPDATE culture_discovery_runs SET status='failed',error='Папярэдні пошук перарваўся',finished_at=? WHERE status='running'").bind(now).run();await db.prepare("INSERT INTO culture_discovery_runs (id,status,started_at) VALUES (?,'running',?)").bind(runId,now).run();const known=new Set<string>();const current=await db.prepare('SELECT canonical_key FROM culture_candidates').all<{canonical_key:string}>();for(const x of current.results??[])known.add(x.canonical_key);
  const save=async(s:CandidateSeed)=>{if(known.has(s.canonical_key))return;const x=await db.prepare(`INSERT OR IGNORE INTO culture_candidates (id,canonical_key,kind,title,release_year,author,description,url,banner_source_url,source_label,discovered_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) RETURNING id`).bind(crypto.randomUUID(),s.canonical_key,s.kind,s.title,s.release_year,s.author,s.description,s.url,s.banner_source_url,s.source_label,now).all();found+=x.results?.length??0;known.add(s.canonical_key)};
  try{const m=await movieSeeds(state.movie_offset);for(const x of m.items)await save(x);await db.prepare("UPDATE culture_discovery_state SET movie_offset=? WHERE id='main'").bind(m.next).run()}catch(e){warnings.push(e instanceof Error?e.message:'Kinakipa недаступная')}
  try{const b=await bookSeeds(state.book_page);for(const x of b.items)await save(x);await db.prepare("UPDATE culture_discovery_state SET book_page=? WHERE id='main'").bind(b.next).run()}catch(e){warnings.push(e instanceof Error?e.message:'Gutenberg недаступны')}
  const status=warnings.length?(warnings.length===2?'failed':'partial'):'complete';await db.prepare('UPDATE culture_discovery_runs SET status=?,found_count=?,error=?,finished_at=? WHERE id=?').bind(status,found,warnings.join(' · ')||null,new Date().toISOString(),runId).run();return{found,status,warnings}
 }finally{await db.prepare("UPDATE culture_discovery_state SET lease_until=? WHERE id='main' AND lease_until=?").bind(new Date(Date.now()+2000).toISOString(),lease).run()}
}
export async function copyCandidateBanner(source:string|null){if(!source)return null;const u=new URL(source);if(!['https:'].includes(u.protocol))return null;const r=await fetch(u.toString(),{headers,signal:AbortSignal.timeout(15000)});if(!r.ok||!r.body)return null;const length=Number(r.headers.get('content-length')||0);if(length>4_000_000)return null;const bytes=new Uint8Array(await r.arrayBuffer());if(bytes.length>4_000_000)return null;const type=r.headers.get('content-type')?.split(';')[0];if(!type||!['image/png','image/jpeg','image/webp'].includes(type))return null;const id=crypto.randomUUID();await (env as unknown as {LOGOS:R2Bucket}).LOGOS.put(`culture-${id}`,bytes,{httpMetadata:{contentType:type}});return `/api/culture-banner?id=${id}`}
