import type {Locale} from './locale';
export const topicSlugs=['bloggers','movies','books'] as const;
export type Topic=typeof topicSlugs[number];
export const discoveryCopy={
 en:{bloggers:'Belarusian-language creators',movies:'Films and animation in Belarusian',books:'Books in Belarusian',intro:{bloggers:'Discover creators covering culture, gaming, history and everyday life. Choose a channel and explore new voices in Belarusian.',movies:'Films and animation in Belarusian: discover titles in the catalog and follow links to watch them.',books:'Books in Belarusian: discover titles and authors, read descriptions and follow links to the source.'},home:'Back to home',catalog:'Catalog',latest:'Latest video',play:'Load YouTube player',privacy:'Clicking connects your browser to YouTube.',watch:'Watch on YouTube',games:'Games this creator has played',emptyGames:'The confirmed games list has not been added yet.',source:'Supporting video',empty:'There are no published items in this topic yet.',unavailable:'The latest video could not be retrieved. You can open the channel on YouTube.',noVideo:'No published videos found yet.',stale:'Showing the last saved data.',followers:'Subscribers',next:'Next',previous:'Previous',open:'Open source',published:'Published',checked:'Checked',disabled:'The creator has disabled embedded playback for this video.'},
 be:{bloggers:'Беларускамоўныя блогеры',movies:'Кіно і мультфільмы па-беларуску',books:'Кнігі па-беларуску',intro:{bloggers:'Знаходзьце аўтараў пра культуру, гульні, гісторыю і штодзённае жыццё. Абірайце канал і адкрывайце новыя галасы па-беларуску.',movies:'Фільмы і мультфільмы на беларускай мове: знаходзьце творы ў каталогу і пераходзьце да крыніцы прагляду.',books:'Кнігі на беларускай мове: адкрывайце назвы і аўтараў, чытайце апісанні і пераходзьце да крыніцы.'},home:'На галоўную',catalog:'Каталог',latest:'Апошняе відэа',play:'Загрузіць прайгравальнік YouTube',privacy:'Пасля націскання ваш браўзер злучыцца з YouTube.',watch:'Глядзець на YouTube',games:'У якія гульні гуляе аўтар',emptyGames:'Пацверджаны спіс гульняў яшчэ не запоўнены.',source:'Відэа-пацвярджэнне',empty:'У гэтай тэме пакуль няма апублікаваных матэрыялаў.',unavailable:'Не ўдалося атрымаць апошняе відэа. Канал можна адкрыць на YouTube.',noVideo:'Апублікаваных відэа пакуль не знойдзена.',stale:'Паказваем апошнія захаваныя даныя.',followers:'Падпісантаў',next:'Далей',previous:'Назад',open:'Адкрыць крыніцу',published:'Апублікавана',checked:'Праверана',disabled:'Аўтар не дазволіў убудаваны прагляд гэтага відэа.'},
 uk:{bloggers:'Білоруськомовні блогери',movies:'Кіно та мультфільми білоруською',books:'Книжки білоруською',intro:{bloggers:'Знаходьте авторів про культуру, ігри, історію та повсякденне життя. Обирайте канал і відкривайте нові голоси білоруською.',movies:'Фільми та мультфільми білоруською мовою: знаходьте твори в каталозі та переходьте до джерела перегляду.',books:'Книжки білоруською мовою: відкривайте назви й авторів, читайте описи та переходьте до джерела.'},home:'На головну',catalog:'Каталог',latest:'Останнє відео',play:'Завантажити програвач YouTube',privacy:'Після натискання ваш браузер з’єднається з YouTube.',watch:'Дивитися на YouTube',games:'В які ігри грає автор',emptyGames:'Підтверджений список ігор ще не заповнено.',source:'Відео-підтвердження',empty:'У цій темі поки немає опублікованих матеріалів.',unavailable:'Не вдалося отримати останнє відео. Канал можна відкрити на YouTube.',noVideo:'Опублікованих відео поки не знайдено.',stale:'Показуємо останні збережені дані.',followers:'Підписників',next:'Далі',previous:'Назад',open:'Відкрити джерело',published:'Опубліковано',checked:'Перевірено',disabled:'Автор не дозволив вбудований перегляд цього відео.'},
 ru:{bloggers:'Белорусскоязычные блогеры',movies:'Кино и мультфильмы на белорусском',books:'Книги на белорусском',intro:{bloggers:'Находите авторов о культуре, играх, истории и повседневной жизни. Выбирайте канал и открывайте новые голоса на белорусском.',movies:'Фильмы и мультфильмы на белорусском языке: находите произведения в каталоге и переходите к источнику просмотра.',books:'Книги на белорусском языке: открывайте названия и авторов, читайте описания и переходите к источнику.'},home:'На главную',catalog:'Каталог',latest:'Последнее видео',play:'Загрузить проигрыватель YouTube',privacy:'После нажатия ваш браузер соединится с YouTube.',watch:'Смотреть на YouTube',games:'В какие игры играет автор',emptyGames:'Подтверждённый список игр ещё не заполнен.',source:'Видео-подтверждение',empty:'В этой теме пока нет опубликованных материаловлов.',unavailable:'Не удалось получить последнее видео. Канал можно открыть на YouTube.',noVideo:'Опубликованные видео пока не найдены.',stale:'Показываем последние сохранённые данные.',followers:'Подписчиков',next:'Далее',previous:'Назад',open:'Открыть источник',published:'Опубликовано',checked:'Проверено',disabled:'Автор не разрешил встроенный просмотр этого видео.'}
} satisfies Record<Locale,unknown>;
