'use client';
import { useCallback,useEffect,useState } from 'react';
import { ArrowLeft,BookOpen,Clapperboard,ImagePlus,Loader2,Save,Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import type { CultureItem,CultureKind } from '@/lib/culture-items';
import DiscoveryPanel from './discovery-panel';

const empty={kind:'movie' as CultureKind,title:'',release_year:new Date().getFullYear(),author:'',description:'',url:'',status:'published' as const};
export default function CultureClient(){
 const [items,setItems]=useState<CultureItem[]>([]),[form,setForm]=useState(empty),[banner,setBanner]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{const r=await fetch('/api/admin/culture-items',{cache:'no-store'});if(r.ok)setItems(((await r.json()) as {items:CultureItem[]}).items)},[]);
 useEffect(()=>{void load()},[load]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');const r=await fetch('/api/admin/culture-items',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const data=await r.json().catch(()=>null) as {id?:string;error?:string}|null;if(!r.ok||!data?.id){setError(data?.error??'Не ўдалося захаваць');setBusy(false);return}if(banner){const upload=await fetch(`/api/culture-banner?item=${encodeURIComponent(data.id)}`,{method:'POST',headers:{'content-type':banner.type},body:banner});if(!upload.ok)setError(((await upload.json().catch(()=>null)) as {error?:string}|null)?.error??'Запіс створаны, але банэр не загрузіўся')}setForm(empty);setBanner(null);await load();setBusy(false)};
 const remove=async(id:string)=>{if(!confirm('Выдаліць гэты запіс?'))return;await fetch(`/api/admin/culture-items?id=${encodeURIComponent(id)}`,{method:'DELETE'});await load()};
 return <main className="site-shell min-h-screen text-foreground"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#111821]/92"><div className="mx-auto flex h-18 max-w-6xl items-center gap-4 px-5"><a href="/" className="text-2xl font-black text-white">КОШ<span className="text-primary">.</span></a><span className="text-sm text-white/35">/ Кіно і кнігі</span><Button render={<a href="/admin"/>} variant="ghost" className="ml-auto rounded-full text-white/65"><ArrowLeft className="size-4"/>Адмінка</Button></div></header><div className="mx-auto max-w-6xl px-5 py-10"><DiscoveryPanel/>
 <form onSubmit={create} className="rounded-3xl border border-white/10 bg-white/4 p-6"><h1 className="text-2xl font-black">Дадаць у культурны каталог</h1><div className="mt-6 grid gap-4 md:grid-cols-2">
 <label className="text-sm text-white/60">Тып<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value as CultureKind})} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-[#151b24] px-3 text-white"><option value="movie">Кіно / мультфільм</option><option value="book">Кніга</option></select></label>
 <label className="text-sm text-white/60">Год выпуску<Input required type="number" min="1000" max="2100" value={form.release_year} onChange={e=>setForm({...form,release_year:Number(e.target.value)})} className="mt-2"/></label>
 <label className="text-sm text-white/60">Назва<Input required maxLength={180} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="mt-2"/></label>
 <label className="text-sm text-white/60">Аўтар / рэжысёр<Input required maxLength={180} value={form.author} onChange={e=>setForm({...form,author:e.target.value})} className="mt-2"/></label>
 <label className="text-sm text-white/60 md:col-span-2">Апісанне<textarea required maxLength={1600} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="mt-2 min-h-28 w-full rounded-xl border border-white/10 bg-white/5 p-3 text-white"/></label>
 <label className="text-sm text-white/60">Спасылка на прагляд або краму<Input required type="url" value={form.url} onChange={e=>setForm({...form,url:e.target.value})} className="mt-2"/></label>
 <label className="text-sm text-white/60">Банэр<Input required type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setBanner(e.target.files?.[0]??null)} className="mt-2 file:text-white"/><span className="mt-1 block text-xs text-white/35">PNG, JPEG або WebP · да 4 МБ</span></label>
 </div>{error&&<p className="mt-4 text-sm text-red-300">{error}</p>}<Button type="submit" disabled={busy} className="mt-5 rounded-full">{busy?<Loader2 className="size-4 animate-spin"/>:<Save className="size-4"/>}{busy?'Захоўваем…':'Дадаць'}</Button></form>
 <section className="mt-10"><h2 className="text-xl font-bold">Ужо дададзена</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{items.map(i=><article key={i.id} className="relative min-h-64 overflow-hidden rounded-2xl border border-white/10 bg-white/4">{i.banner_url?<img src={i.banner_url} alt="" className="absolute inset-0 h-full w-full object-cover"/>:<div className="absolute inset-0 grid place-items-center text-white/20"><ImagePlus className="size-12"/></div>}<div className="absolute inset-0 bg-gradient-to-t from-black via-black/55 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-5"><div className="flex items-center gap-2 text-xs text-secondary">{i.kind==='movie'?<Clapperboard className="size-4"/>:<BookOpen className="size-4"/>}{i.kind==='movie'?'Кіно':'Кніга'} · {i.release_year}</div><h3 className="mt-2 text-xl font-bold">{i.title}</h3><p className="text-sm text-white/60">{i.author}</p></div><Button type="button" size="icon" variant="destructive" aria-label="Выдаліць" onClick={()=>void remove(i.id)} className="absolute right-3 top-3 rounded-full"><Trash2 className="size-4"/></Button></article>)}</div>{!items.length&&<p className="mt-4 rounded-2xl border border-dashed border-white/10 py-10 text-center text-white/35">Запісаў пакуль няма</p>}</section>
 </div></main>
}
