'use client';
import { useCallback,useEffect,useState } from 'react';
import { BookOpen,Check,Clapperboard,ExternalLink,RefreshCw,X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import type { CultureCandidate } from '@/lib/culture-discovery';
type Run={started_at:string;status:string;found_count:number;error:string|null};
function Card({item,reload}:{item:CultureCandidate;reload:()=>Promise<void>}){
 const [title,setTitle]=useState(item.title),[year,setYear]=useState(item.release_year),[author,setAuthor]=useState(item.author),[description,setDescription]=useState(item.description),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function review(status:'approved'|'rejected'){setBusy(true);setError('');try{const r=await fetch('/admin/api/culture-discovery',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:item.id,status,confirmed,title,release_year:year,author,description})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error??'Не ўдалося апрацаваць');await reload()}catch(e){setError(e instanceof Error?e.message:'Памылка злучэння')}finally{setBusy(false)}}
 return <article className="grid gap-5 rounded-2xl border border-white/10 bg-black/15 p-5 md:grid-cols-[180px_1fr]">{item.banner_source_url?<img src={item.banner_source_url} alt="" className="aspect-[4/5] w-full rounded-xl object-cover"/>:<div className="grid aspect-[4/5] place-items-center rounded-xl bg-white/5 text-white/25">{item.kind==='movie'?<Clapperboard/>:<BookOpen/>}</div>}<div className="space-y-4"><div className="flex flex-wrap items-center gap-3 text-sm"><strong className="text-secondary">{item.kind==='movie'?'Кіно':'Кніга'}</strong><span className="text-white/45">{item.source_label}</span><a href={item.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-white/70 underline">Адкрыць крыніцу <ExternalLink className="size-3.5"/></a></div>{item.status==='pending'?<><div className="grid gap-3 sm:grid-cols-[1fr_130px]"><label className="text-sm text-white/60">Назва<Input value={title} onChange={e=>setTitle(e.target.value)} disabled={busy} className="mt-1"/></label><label className="text-sm text-white/60">Год<Input type="number" value={year} onChange={e=>setYear(Number(e.target.value))} disabled={busy} className="mt-1"/></label></div><label className="block text-sm text-white/60">Аўтар / рэжысёр<Input value={author} onChange={e=>setAuthor(e.target.value)} disabled={busy} className="mt-1"/></label><label className="block text-sm text-white/60">Апісанне<textarea value={description} onChange={e=>setDescription(e.target.value)} disabled={busy} className="mt-1 min-h-28 w-full rounded-xl border border-white/10 bg-white/5 p-3 text-white"/></label><label className="flex cursor-pointer items-start gap-3 text-sm leading-relaxed text-white/75"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)} disabled={busy}/>Я адкрыў(-ла) крыніцу і пацвярджаю даныя, банэр і наяўнасць беларускай версіі.</label><div className="flex flex-wrap gap-3"><Button type="button" disabled={busy||!confirmed} onClick={()=>void review('approved')} className="rounded-full bg-emerald-600 hover:bg-emerald-700"><Check className="size-4"/>Прыняць у каталог</Button><Button type="button" disabled={busy} onClick={()=>void review('rejected')} variant="outline" className="rounded-full"><X className="size-4"/>Адхіліць</Button></div></>:<p className="font-semibold">{item.status==='approved'?'Прынята ў каталог':'Адхілена'}</p>}{error&&<p role="alert" className="text-sm text-red-200">{error}</p>}</div></article>
}
export default function DiscoveryPanel(){
 const [candidates,setCandidates]=useState<CultureCandidate[]>([]),[lastRun,setLastRun]=useState<Run|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[archived,setArchived]=useState(false);
 const load=useCallback(async()=>{const r=await fetch('/admin/api/culture-discovery',{cache:'no-store'});const d=await r.json() as {candidates?:CultureCandidate[];lastRun?:Run;error?:string};if(!r.ok)throw new Error(d.error??'Не ўдалося загрузіць чаргу');setCandidates(d.candidates??[]);setLastRun(d.lastRun??null);setLoading(false)},[]);
 useEffect(()=>{void load().catch(e=>{setError(e.message);setLoading(false)})},[load]);
 async function run(){setBusy(true);setError('');try{const r=await fetch('/admin/api/culture-discovery',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'run'})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error??'Пошук недаступны');await load()}catch(e){setError(e instanceof Error?e.message:'Памылка злучэння')}finally{setBusy(false)}}
 const visible=candidates.filter(x=>archived?x.status!=='pending':x.status==='pending');
 return <section className="mb-10 rounded-3xl border border-white/10 bg-white/4 p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-secondary">Аўтаматычны пошук</p><h1 className="mt-2 text-2xl font-black">Новыя фільмы і кнігі</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-white/55">Пошук правярае адкрытыя каталогі Kinakipa і Gutenberg. Нічога не публікуецца без вашага пацвярджэння; усе палі можна выправіць перад прыняццем.</p></div><Button type="button" disabled={busy||loading} onClick={()=>void run()} className="shrink-0 rounded-full"><RefreshCw className={`size-4 ${busy?'animate-spin':''}`}/>{busy?'Шукаем…':'Знайсці наступныя'}</Button></div>{lastRun&&<p className="mt-4 text-sm text-white/45">{new Date(lastRun.started_at).toLocaleString('be-BY')} · новых кандыдатаў: {lastRun.found_count}{lastRun.error?` · ${lastRun.error}`:''}</p>}{error&&<p role="alert" className="mt-4 text-sm text-red-200">{error}</p>}<div className="mt-5 flex gap-2"><Button type="button" variant={!archived?'default':'outline'} onClick={()=>setArchived(false)} className="rounded-full">Чарга · {candidates.filter(x=>x.status==='pending').length}</Button><Button type="button" variant={archived?'default':'outline'} onClick={()=>setArchived(true)} className="rounded-full">Архіў</Button></div><div className="mt-5 space-y-4">{loading?<p className="py-8 text-center text-white/40">Загрузка…</p>:visible.length?visible.map(x=><Card key={x.id} item={x} reload={load}/>):<p className="rounded-2xl border border-dashed border-white/10 py-10 text-center text-white/35">{archived?'Архіў пусты':'Новых кандыдатаў пакуль няма'}</p>}</div></section>
}
