import { ensureCultureItemsTable,type CultureItem,type CultureKind } from '@/lib/culture-items';
const OWNER='radziuk219@gmail.com';
const owner=(r:Request)=>(r.headers.get('cf-access-authenticated-user-email')??r.headers.get('oai-authenticated-user-email'))?.toLowerCase()===OWNER;
const origin=(r:Request)=>!r.headers.get('origin')||r.headers.get('origin')===new URL(r.url).origin;
function input(value:unknown){
 const b=value as Record<string,unknown>|null; const kind=b?.kind==='movie'||b?.kind==='book'?b.kind as CultureKind:null,title=typeof b?.title==='string'?b.title.trim():'',release_year=Number(b?.release_year),author=typeof b?.author==='string'?b.author.trim():'',description=typeof b?.description==='string'?b.description.trim():'',url=typeof b?.url==='string'?b.url.trim():'',status=b?.status==='hidden'?'hidden' as const:'published' as const;let safe=false;try{safe=['http:','https:'].includes(new URL(url).protocol)}catch{}
 return kind&&title&&title.length<=180&&Number.isInteger(release_year)&&release_year>=1000&&release_year<=2100&&author&&author.length<=180&&description&&description.length<=1600&&safe?{kind,title,release_year,author,description,url,status}:null
}
export async function GET(r:Request){if(!owner(r))return Response.json({error:'Няма доступу'},{status:403});const db=await ensureCultureItemsTable(),x=await db.prepare('SELECT * FROM culture_items ORDER BY updated_at DESC').all<CultureItem>();return Response.json({items:x.results??[]})}
export async function POST(r:Request){if(!origin(r)||!owner(r))return Response.json({error:'Няма доступу'},{status:403});const v=input(await r.json().catch(()=>null));if(!v)return Response.json({error:'Праверце ўсе палі, год і спасылку'},{status:400});const id=crypto.randomUUID(),now=new Date().toISOString(),db=await ensureCultureItemsTable();await db.prepare('INSERT INTO culture_items (id,kind,title,release_year,author,description,url,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id,v.kind,v.title,v.release_year,v.author,v.description,v.url,v.status,now,now).run();return Response.json({id},{status:201})}
export async function PATCH(r:Request){if(!origin(r)||!owner(r))return Response.json({error:'Няма доступу'},{status:403});const b=await r.json().catch(()=>null) as Record<string,unknown>|null,id=typeof b?.id==='string'?b.id:'',v=input(b);if(!id||!v)return Response.json({error:'Праверце ўсе палі, год і спасылку'},{status:400});const db=await ensureCultureItemsTable(),x=await db.prepare('UPDATE culture_items SET kind=?,title=?,release_year=?,author=?,description=?,url=?,status=?,updated_at=? WHERE id=?').bind(v.kind,v.title,v.release_year,v.author,v.description,v.url,v.status,new Date().toISOString(),id).run();return x.meta.changes?Response.json({id}):Response.json({error:'Запіс не знойдзены'},{status:404})}
export async function DELETE(r:Request){if(!origin(r)||!owner(r))return Response.json({error:'Няма доступу'},{status:403});const id=new URL(r.url).searchParams.get('id')??'',db=await ensureCultureItemsTable();await db.prepare('DELETE FROM culture_items WHERE id=?').bind(id).run();return Response.json({id,deleted:true})}
